const Router = require("express").Router()

const PublisherRouter = require("./PublisherRoutes")
const CategoryRouter = require("./CategoryRoutes")
const SubcategoryRouter = require("./SubcategoryRoutes")
const TestimonialRouter = require("./TestimonialRoutes")
const UserRouter = require("./UserRoutes")
const CartRouter = require("./CartRoutes")
const WishlistRouter = require("./WishlistRoutes")
const CheckoutRouter = require("./CheckoutRoutes")
const NewsletterRouter = require("./NewsletterRoutes")
const ContactUsRouter = require("./ContactUsRoutes")
const InvoiceRouter = require("./InvoiceRoutes")
const BookRouter = require("./BooksRoutes")
const BannerRouter = require("./BannerRoutes")

Router.use("/category", CategoryRouter)
Router.use("/subcategory", SubcategoryRouter)
Router.use("/publisher", PublisherRouter)
Router.use("/testimonial", TestimonialRouter)
Router.use("/book", BookRouter)
Router.use("/user", UserRouter)
Router.use("/cart", CartRouter)
Router.use("/wishlist", WishlistRouter)
Router.use("/checkout", CheckoutRouter)
Router.use("/newsletter", NewsletterRouter)
Router.use("/contactus", ContactUsRouter)
Router.use("/invoice", InvoiceRouter)
Router.use("/banner", BannerRouter)

module.exports = Router